// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: hashing/pb/hashing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CreateHashRequest) Reset() {
	*x = CreateHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashing_pb_hashing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashRequest) ProtoMessage() {}

func (x *CreateHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashing_pb_hashing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashRequest.ProtoReflect.Descriptor instead.
func (*CreateHashRequest) Descriptor() ([]byte, []int) {
	return file_hashing_pb_hashing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHashRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CreateHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *CreateHashResponse) Reset() {
	*x = CreateHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashing_pb_hashing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashResponse) ProtoMessage() {}

func (x *CreateHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashing_pb_hashing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashResponse.ProtoReflect.Descriptor instead.
func (*CreateHashResponse) Descriptor() ([]byte, []int) {
	return file_hashing_pb_hashing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CheckHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CheckHashRequest) Reset() {
	*x = CheckHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashing_pb_hashing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHashRequest) ProtoMessage() {}

func (x *CheckHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hashing_pb_hashing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHashRequest.ProtoReflect.Descriptor instead.
func (*CheckHashRequest) Descriptor() ([]byte, []int) {
	return file_hashing_pb_hashing_proto_rawDescGZIP(), []int{2}
}

func (x *CheckHashRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CheckHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashExists bool `protobuf:"varint,1,opt,name=hash_exists,json=hashExists,proto3" json:"hash_exists,omitempty"`
}

func (x *CheckHashResponse) Reset() {
	*x = CheckHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashing_pb_hashing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHashResponse) ProtoMessage() {}

func (x *CheckHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hashing_pb_hashing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHashResponse.ProtoReflect.Descriptor instead.
func (*CheckHashResponse) Descriptor() ([]byte, []int) {
	return file_hashing_pb_hashing_proto_rawDescGZIP(), []int{3}
}

func (x *CheckHashResponse) GetHashExists() bool {
	if x != nil {
		return x.HashExists
	}
	return false
}

var File_hashing_pb_hashing_proto protoreflect.FileDescriptor

var file_hashing_pb_hashing_proto_rawDesc = []byte{
	0x0a, 0x18, 0x68, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x68, 0x61, 0x73,
	0x68, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x34, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x61, 0x73,
	0x68, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x32, 0x78, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x69,
	0x6e, 0x67, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x11, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hashing_pb_hashing_proto_rawDescOnce sync.Once
	file_hashing_pb_hashing_proto_rawDescData = file_hashing_pb_hashing_proto_rawDesc
)

func file_hashing_pb_hashing_proto_rawDescGZIP() []byte {
	file_hashing_pb_hashing_proto_rawDescOnce.Do(func() {
		file_hashing_pb_hashing_proto_rawDescData = protoimpl.X.CompressGZIP(file_hashing_pb_hashing_proto_rawDescData)
	})
	return file_hashing_pb_hashing_proto_rawDescData
}

var file_hashing_pb_hashing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hashing_pb_hashing_proto_goTypes = []interface{}{
	(*CreateHashRequest)(nil),  // 0: CreateHashRequest
	(*CreateHashResponse)(nil), // 1: CreateHashResponse
	(*CheckHashRequest)(nil),   // 2: CheckHashRequest
	(*CheckHashResponse)(nil),  // 3: CheckHashResponse
}
var file_hashing_pb_hashing_proto_depIdxs = []int32{
	0, // 0: Hashing.CreateHash:input_type -> CreateHashRequest
	2, // 1: Hashing.CheckHash:input_type -> CheckHashRequest
	1, // 2: Hashing.CreateHash:output_type -> CreateHashResponse
	3, // 3: Hashing.CheckHash:output_type -> CheckHashResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hashing_pb_hashing_proto_init() }
func file_hashing_pb_hashing_proto_init() {
	if File_hashing_pb_hashing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hashing_pb_hashing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashing_pb_hashing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashing_pb_hashing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hashing_pb_hashing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hashing_pb_hashing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hashing_pb_hashing_proto_goTypes,
		DependencyIndexes: file_hashing_pb_hashing_proto_depIdxs,
		MessageInfos:      file_hashing_pb_hashing_proto_msgTypes,
	}.Build()
	File_hashing_pb_hashing_proto = out.File
	file_hashing_pb_hashing_proto_rawDesc = nil
	file_hashing_pb_hashing_proto_goTypes = nil
	file_hashing_pb_hashing_proto_depIdxs = nil
}
